# Change these first
owner: merlinfuchs # Your GitHub organization or username, where this repository lives
repo: kite-uptime # The name of this repository

sites:
  - name: Kite Website
    url: https://kite.onl/
  - name: Kite API
    url: https://api.kite.onl/v1/health

status-website:
  cname: status.kite.onl
  # baseUrl: /kite-uptime
  logoUrl: https://kite.onl/logo.svg
  favicon: https://kite.onl/logo.png
  faviconSvg: https://kite.onl/logo.svg
  name: Kite Status
  introTitle: "**Kite** is the easiest way to create your own Discord Bot without writing a single line of code."
  introMessage: This page shows the status and uptime of Kite and the related services. If you are looking for the Kite website click [here](https://kite.onl)!
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://kite.onl

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
